version: "3.8"
services:

  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: bankingPcha