package com.bpcha.core_banking_bpcha.domain.model.shared;

public enum TypeExceptions {
    ID_CANNOT_BE_NULL,
    ENTITY_NOT_FOUND_CHECK_ID,
    REQUEST_CANNOT_BE_NULL_CHECK_REQUEST,
    SOME_FIELDS_ARE_NULL_CHECK_THE_REQUEST,
    ENTITY_DOESNT_EXIST_CANNOT_BE_UPDATED,
    ENTITY_DOESNT_EXIST_CANNOT_BE_DELETED,
    INVALID_TYPE_TRANSACTION
}
