spring:
  devtools:
    livereload.enabled: true
  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL8Dialect

    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost/banking-pcha?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.hibernate:
      sql: debug
      type.descriptor.sql.basic-binder: trace

config:
  security:
    user: "admin"
    password: "admin123"